controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

fichier:
  path: /fichier/{correction}
  controller: App\Controller\FichierController::correction